[package]
name = "simconnect"
license = "MIT"
description = "Rust bindings for SimConnect"
version = "0.5.0"
authors = ["Connor T"]
edition = "2021"

[dependencies]
simconnect-fs2020 = { path = "simulators/FS2020", optional = true }
simconnect-fs2024 = { path = "simulators/FS2024", optional = true }

[features]
default = ["all"]
fs2020 = ["dep:simconnect-fs2020"]
fs2024 = ["dep:simconnect-fs2024"]
all = ["fs2020", "fs2024"]
